### ISSUE TITLE
App freezes when performing consult xfer

### ISSUE THREAD

**Issue by ppulham** [LubosD/twinkle#118]
When trying to perform a consult xfer using twinkle 1.10.1 the application freezes.

Observed behaviour:

Call inbound and answered.
Xfer button pressed and consult transfer to number
Line 1 successfully goes on hold
Line 2 answers
Unable to complete transfer, app has to be forcibly closed.

Behaviour is the same as this https://github.com/LubosD/twinkle/issues/73

Blind xfer works fine.

**Comment by fbriere** [comment]
I tried to reproduce this, without any success.

Could you provide a backtrace of Twinkle when it is hanging?  This would require you to either recompile with `-DCMAKE_BUILD_TYPE=Debug`, or install the corresponding debug symbols package provided by your distribution (`twinkle-dbgsym` for Debian/Ubuntu).  Then, after installing `gdb`, you:

- Run `gdb twinkle`
- Type `set logging on`
- Type `run`
- Perform a xfer and make Twinkle hang
- Press CTRL and `\`
- Type `thread apply all bt`
- Type `quit`

You can then send us a copy of the `gdb.txt` file that was created; this should tell us exactly where in the code Twinkle is hanging.

Thanks!

**Comment by ppulham** [comment]
[gdb.txt](https://github.com/LubosD/twinkle/files/1839121/gdb.txt)

Hopefully this is what you're after. 

Thanks.

**Comment by fbriere** [comment]
Strange, there's only one thread in this backtrace.  Could it be that you did a simple `bt`, instead of `thread apply all bt`?

Anyway, the backtrace seems to indicate that the freeze occurs within PulseAudio; this would certainly explain why I wasn't able to recreate it.  (Could anyone else running PulseAudio comment on whether or not they are also affected by this?)

Unfortunately, this is probably beyond my ability, so you will have to wait for someone more knowledgeable than me to take a stab at this issue.  In the meantime, just in case this information could be helpful to that person, could you provide another backtrace with the debug symbols for ALSA and PulseAudio?  (For Debian/Ubuntu, the packages would be `libasound2-dbgsym`, `libasound2-plugins-dbgsym` and `libpulse0-dbgsym`.)

**Comment by fbriere** [comment]
(Adding reference links to #9 and #103 as other issues related to PulseAudio.)

**Comment by fbriere** [comment]
Forget what I said before, this has nothing to do with PulseAudio, but is rather a Twinkle bug.  (I was misled by the incomplete backtrace.)

This is one of several deadlocks I have identified in #165, and will occur when performing a consult transfer if the target does not support the `Replaces` SIP extension.  (In Twinkle, this can be enabled/disabled in each user profile, under "SIP protocol", "General", "SIP extensions".)

Ironically enough, Twinkle will also deadlock if it is the target of a consult transfer using `Replaces`.  So, if you are using Twinkle to transfer someone to another Twinkle user, one of the two will freeze either way.  :frowning_face:
