### ISSUE TITLE
impossible to answer or reject calls with the pop up gui

### ISSUE THREAD

**Issue by unnilennium** [LubosD/twinkle#120]
as reported a while back on Fedora bug tracker : https://bugzilla.redhat.com/show_bug.cgi?id=1436263

The popup display correctly in the middle of the screen, however I am not able to answer: clicking on the buttons nothing happen. 
If th emain windows is open I can answerwithout issue using the main window buttons.

**Comment by fbriere** [comment]
Just to confirm: if the main window is visible, is the popup still inoperative?

**Comment by fbriere** [comment]
Note: As per the original bug report, this is under GNOME 3.  Are there any other users who can comment on whether or not they are affected by this?

**Comment by fbriere** [comment]
After spending the whole day tracking this, I have some good news and some bad news for you.  :smile:

The good news is that there is indeed a bug with the incoming call popup, which causes Qt to print an error message whenever one of the two buttons is pressed.  (Why did I never notice this?)  I have submitted #164 as a fix.

The bad news is that I was never able to recreate the behavior you encountered, to prove that this bug was indeed the cause of your problem, and that fixing it was the answer.  I tried installing Fedora 29 (25-27 were no longer available) in VirtualBox, but I had no success whether using "GNOME", "GNOME Classic" or "GNOME on Xorg", and whether Twinkle was truly minimized or hidden in the (non-existent) systray.  I figured maybe Qt had learned to better deal with this mistake of ours since then, but I had no success on Debian "stretch" either, which has the same Qt version as Fedora 25.

So, while I did fix a bug, and while it looks very likely to be the bug you encountered, I cannot prove this with 100% certainty.  Nevertheless, I'll assume it is, but if you could give it a try and confirm this, it would be greatly appreciated.  Thanks!
