### ISSUE TITLE
twinkle fails tobuild against new Qt5 >= 5.11

### ISSUE THREAD

**Issue by david-geiger** [LubosD/twinkle#124]
Hi,

Since new Qt5 5.11 twinkle doesn't built anymore, so this following patch fixes this issue:

http://svnweb.mageia.org/packages/cauldron/twinkle/current/SOURCES/twinkle-1.10.1-fix-build-against-qt-5.11.0.patch?view=markup&pathrev=1233547

Regards,
David

**Comment by mkubecek** [comment]
Ah, I noticed recent build failures in openSUSE Factory but didn't look into it more closely yet as they were only on ppc64(le) and ARM. Apparently we already have Qt 5.11 on these architectures and 5.10 on x86_64 and i586.

The include file seems to exist at least since Qt 5.6 so it should be safe to include it explicitly even with pre-5.11 versions. I'll run some test builds to make sure.

**Comment by mkubecek** [comment]
Looking more closely, it seems unlikely that adding the include only to `src/gui/getprofilenameform.cpp` would suffice when the class is also used in 7 other files. Let me check...

**Comment by mkubecek** [comment]
So the difference is that with Qt 5.11, generated `ui_getprofilename.h` does not include `<QHeaderView>` which, after a long chain, eventually include `qvalidator.h`. The other files using `QRegExpValidator` probably include some headers which end up including `qvalidator.h` but it seems rather fragile to rely upon it. Explicitly including `<QRegExpValidtor>` in each file using `QRegExpValidator` class feels safer.

**Comment by mkubecek** [comment]
The fix is merged, I believe we can close.
