### ISSUE TITLE
Change GUI language

### ISSUE THREAD

**Issue by swamp-fish** [LubosD/twinkle#133]
Hi. I've noticed that there're some translations but how do i apply them? There seems to be no way to change GUI language neither from GUI nor from console.

**Comment by swamp-fish** [comment]
Ok, i can change it with LANG variable, did't think about before posting. Some gui way would be nice though.

**Comment by fbriere** [comment]
`$LANG` is indeed how Unix applications are told which language (or locale, to be exact) they should use.  Typically, your distribution and/or desktop environment will provide a user-friendly way to set this variable for all applications (and generate the corresponding locale if necessary).

(Now, there *are* applications that provide their own language setting, such as Firefox or LibreOffice, but this is apparently because of their presence on Windows, where selecting the language via the system can be a PITA, or so I've been lead to believe.)
