### ISSUE TITLE
Cannot write configuration when there's a slash in the profile name

### ISSUE THREAD

**Issue by rreuvekamp** [LubosD/twinkle#189]
Slashes in the profile name seem to not get escaped when using it as the directory name for the configuration. This makes you unable to save the configuration.

Screenshot of the error: https://framapic.org/NMuvhQXmZDj8/uCvdqfmuhG46.png

It would be great if slashes would either be escaped when using it to determine a configuration directory. Or, if an error message would be shown when trying to create a profile with a slash in the name.

I'm using version:Twinkle 1.10.1 - 07 October 2016
It came from the Debian buster repo's.

Hope this is useful,

Thanks for making Twinkle!

**Comment by fbriere** [comment]
There is indeed a check in Twinkle for which characters are allowed in a profile name, but it was no longer invoked (probably lost in the Great Qt Transition of 2015).  I added it back in #203, along with other fixes and enhancements (such as explicitly listing what those characters actually are).

Do note that this check is rather restrictive, allowing only letters, digits, `-`, `_`, `.` and `@` (the latter two not being permitted as initial character).  This means that the profile name shown in your example would have been rejected not only due to the `/`, but the spaces as well.  (I can't speak about the reasons behind this particular selection; I merely left it as-is.)

**Comment by rreuvekamp** [comment]
Great! Thanks for the fix!
