### ISSUE TITLE
Location of preprocessing settings values

### ISSUE THREAD

**Issue by RafaJurado** [LubosD/twinkle#314]
Hi. I'm configuring Twinkle as a terminal softphone. I've configured a user profile to make and receive calls that will be remotely controlled, but i couldn't find any trace of the location for the preprocessing settings that can be set with the ui, that's the VAD configuration, the echo cancellation, automatic gain control and noise reduction. Using the ui in another pc I can set these values in the usual way (profile settings, rtp audio, Preprocessing tab) and the values are there after closing and reopening the app, so they are stored somewhere (not in `twinkle.sys` or in `<profile>.cfg`, for sure). So the mistery (for me) is where is this configuration stored?. 

BTW: thank you for such a great app, works great for my necessities.

Edit: forgot to describe the context:
Twinkle 1.10.1 on Ubuntu 18.04.6, 5.15.0-48-generic

**Comment by fbriere** [comment]
> (not in `twinkle.sys` or in `<profile>.cfg`, for sure)

Oh, you shouldn't be so sure, because they *are* in the `.cfg` file.  :grin:  Namely, those are the various `speex_dsp_*` variables under the `RTP AUDIO` section.  (The names are heavily abbreviated, but you can probably figure out which acronym is which.)

> BTW: thank you for such a great app, works great for my necessities.

Glad to hear it, and you are very much welcome!
