### ISSUE TITLE
Release twinkle for Qt 5.6 compatibility

### ISSUE THREAD

**Issue by petercolberg** [LubosD/twinkle#64]
Now that Qt 5.6 has been released, could you release a new twinkle version that includes the fix for #52?

I briefly tested the latest commit 7b4af44 using Qt 5.5 under Debian unstable and it works fine.

**Comment by LubosD** [comment]
Yes, I'll probably make two releases: 1.9.1 with fixes, except the QtQuick change, and 1.10.0 with the QtQuick change.

**Comment by petercolberg** [comment]
Did you have a chance yet at preparing a 1.10.0 release? Let me know whether I can help.

**Comment by petercolberg** [comment]
It would be very nice if you could tag a release.

**Comment by LubosD** [comment]
I will, sorry, too busy :-(

**Comment by petercolberg** [comment]
Could you let me know what needs to be done for a release apart from preparing the changelog? I would like to help since the bug reports against the twinkle package in Debian are accumulating. I would like to avoid packaging a git snapshot, assuming that other distributions are interested in a release, too.

**Comment by petercolberg** [comment]
Any chance we could have a release in July?

**Comment by LubosD** [comment]
Done!

**Comment by petercolberg** [comment]
Thanks!

**Comment by shubhamdiwase** [comment]
Can u guide me to add a new function of break and resume,so that i can use them for my automated script.
Cause everytime using node js wrapper commands are getting specific lag and dropouts.Its running,but want it to be more effecient
And what files to change specifically will be an added advantage
break:
Description
just deregistering the softphone
resume:
registering the softphone.
